### ISSUE TITLE
setDevVersionTycho: push to Bitbucket failing due to REJECTED_NONFASTFORWARD 

### ISSUE THREAD

**Issue by pkoryzna** [shillner/unleash-scm-provider-git#13] opened 2017-12-20 14:11 UTC
Seems like `performTycho` default workflow tried to do something that Bitbucket did not like. I'm trying to run a simple release on a local branch that is pushed to my remote. It fails with the stack trace below when executing `setDevVersionTycho` step. I couldn't find out what exactly causes it to be non-fastforward exactly - any help in tracking down what went wrong would be much appreciated!

I also tried modifying the workflow to run `checkForScmChanges` before `setDevVersionTycho`, hoping that maybe the conflicting commits would get fetched, but that did not help.

```
[INFO] 15:05:49,003  Git - Update finished successfully. New revision is: 6b00c76e1159c71594e51cd98fd023201dcbd112
[ERROR] An exception was caught while processing the workflow step with id 'setDevVersionTycho'.
com.itemis.maven.plugins.unleash.scm.ScmException: Could not push local changes to the remote repository due to the following error: [REJECTED_NONFASTFORWARD] 
    at com.itemis.maven.plugins.unleash.scm.providers.ScmProviderGit.push (ScmProviderGit.java:403)
    at com.itemis.maven.plugins.unleash.scm.providers.ScmProviderGit.commit (ScmProviderGit.java:336)
    at com.itemis.maven.plugins.unleash.util.DevVersionUtil.commitChanges (DevVersionUtil.java:108)
    at com.itemis.maven.plugins.unleash.steps.actions.tycho.SetDevVersionsTycho.execute (SetDevVersionsTycho.java:69)
    at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.executeSequentialWorkflowStep (WorkflowExecutor.java:157)
    at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.execute (WorkflowExecutor.java:119)
    at com.itemis.maven.plugins.cdi.AbstractCDIMojo.execute (AbstractCDIMojo.java:209)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:47)
[INFO] Rolling back after execution errors - please find the error messages and stack traces above.
[INFO] 15:05:53,151  Rollback of all version changes necessary for the next development cycle (POMs, MANIFESTs, ...).
[ERROR] An exception was caught while rolling back the workflow step with id 'setDevVersionTycho'. Proceeding with the rollback of the next steps.
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.rollback (WorkflowExecutor.java:259)
    at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.rollback (WorkflowExecutor.java:238)
    at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.executeSequentialWorkflowStep (WorkflowExecutor.java:161)
    at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.execute (WorkflowExecutor.java:119)
    at com.itemis.maven.plugins.cdi.AbstractCDIMojo.execute (AbstractCDIMojo.java:209)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:47)
Caused by: java.lang.IllegalStateException: No from revision set (start revision of the reversion)!
    at com.google.common.base.Preconditions.checkState (Preconditions.java:459)
    at com.itemis.maven.plugins.unleash.scm.requests.RevertCommitsRequest$Builder.build (RevertCommitsRequest.java:187)
    at com.itemis.maven.plugins.unleash.steps.actions.tycho.SetDevVersionsTycho.rollback (SetDevVersionsTycho.java:91)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.rollback (WorkflowExecutor.java:259)
    at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.rollback (WorkflowExecutor.java:238)
    at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.executeSequentialWorkflowStep (WorkflowExecutor.java:161)
    at com.itemis.maven.plugins.cdi.internal.util.workflow.WorkflowExecutor.execute (WorkflowExecutor.java:119)
    at com.itemis.maven.plugins.cdi.AbstractCDIMojo.execute (AbstractCDIMojo.java:209)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:47)
```

**Comment by shillner** [comment] 2017-12-21 20:00
Hi I guess that the error message `REJECTED_NONFASTFORWARD` is caused by incoming remote changes that haven't been merged. Actually the remote changes shouldn't cause issues since those are merged automatically prior to the push but something seemed to fail in your constellation.

- Please can you verify that there were incoming changes after the checkout from remote and prior to the push of the local changes done by the plugin?
- Are you running on a `clean` clone of the remote repository? With clean I mean that your local branch is not behind or ahead of the remote branch.
- If there were remote changes between checkout and push during the release, can you somehow reproduce the behavior on a small repository and maybe give some instructions how I may run into this issue?

Thanks

**Comment by mortenlocka** [comment] 2020-01-16 13:08
I got the same issue. For some reason the first release was fine. But the next release fails with:
`com.itemis.maven.plugins.unleash.scm.ScmException: Could not push local changes to the remote repository due to the following error: [REJECTED_NONFASTFORWARD] 
    at com.itemis.maven.plugins.unleash.scm.providers.ScmProviderGit.push (ScmProviderGit.java:422)
    at com.itemis.maven.plugins.unleash.scm.providers.ScmProviderGit.commit (ScmProviderGit.java:355)
    at com.itemis.maven.plugins.unleash.util.DevVersionUtil.commitChanges (DevVersionUtil.java:108)
    at com.itemis.maven.plugins.unleash.steps.actions.SetNextDevVersion.execute (SetNextDevVersion.java:69)`


We are doing the release from the "develop" branch. And after mvn:unleash is completed. We merge the release-tag back to the master branch. When I removed the git merge of the tag back to master everything works ok. Not sure why.

Resolved this with commitBeforeTag = true, and merge of the commit to master instead of the tag.

**Closed as completed** 2021-06-25 19:46 UTC
